project:
  type: website

website:
  title: "Christopher Antwi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: papers.qmd
        text: Papers
      - href: notes.qmd
        text: Notes
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    toc: true


